
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Dockerfile
FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y curl unzip

# Install ChromeDriver
RUN CHROMEDRIVER_VERSION="94.0.4606.61" && \
    curl -L -O "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" && \
    unzip chromedriver_linux64.zip && \
    chmod +x chromedriver && \
    mv chromedriver /usr/local/bin/

WORKDIR /workspace
