name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: browser-actions/setup-chrome@latest
      - run: |
          VERSION_STRING="106.0.5249.119"
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"


      - name: Build with Maven
        run: mvn test
